server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:address/shareblog? useUnicode=true&characterEncoding=utf8
    username:
    password: 
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: file
  redis:
    host: ip
# Mybatis-Plus 配置
mybatis-plus:
  #  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
 # typeAliasesPackage: com.shareblog.article.mapper;com.shareblog.category.mapper
  global-config:
    id-type: 1  #0:数据库ID自增   1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
jwt:
  config:
    ttl: 3600000

#登录页面地址
login:
  config:
    url: ip

#fastDFS
fdfs:
  so-timeout: 1500 #socket连接超时时长
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - ip:address
